import type { Language } from './translations';
import { lawyerBriefText } from './lawyer-brief';
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx';
import { zipSync, strToU8 } from 'fflate';
import {
  CRITERIA,
  OFFICIAL,
  type CaseData,
  type RecordItem,
} from './case-domain';
import { bindings, hash, HttpError } from './case-store';
export const DOC_TYPES = [
  ['lawyer', '律所沟通包'],
  ['support', '申请支持信'],
  ['work', '赴美工作安排'],
  ['i129', 'I-129 字段工作表'],
  ['ss4', 'SS-4 字段工作表'],
  ['recommendation', '给推荐人的写作要点'],
  ['business', '商业计划事实清单'],
  ['translation', '翻译认证工作单'],
  ['consultation', 'Consultation 判断记录'],
  ['rfe', 'RFE / NOID 响应清单'],
] as const;
export function buildDraft(
  c: CaseData,
  type: string,
  language: Language = 'zh',
) {
  const p = c.project.profile,
    evidence = c.records.filter(
      (r) =>
        r.kind === 'evidence' &&
        r.body.status === 'reviewed' &&
        r.body.confirmed,
    ),
    events = c.records.filter(
      (r) => r.kind === 'event' && r.body.confirmed && !r.body.hypothesis,
    );
  const refs = evidence.map(
    (r, i) =>
      `[E${i + 1}] ${r.body.title} | ${r.body.issuer || '出具人待确认'} | ${r.body.date || '日期待确认'} | ${r.body.page || '页段待确认'}\n${r.body.excerpt}\nSource ID: ${r.id}`,
  );
  const snapshot = `Beneficiary: ${p.name || '[待补充：受益人姓名]'}\nPetitioner: ${p.company || '[待补充：申请主体]'}\nField: ${p.field || '[待补充：领域]'}\nRole: ${p.role || '[待补充：拟任职位]'}\nDuties: ${p.duties || '[待补充：职责]'}\nWork period: ${p.start || '[待补充：开始日]'} — ${p.end || '[待补充：结束日]'}\nWork location: ${p.workplace || '[待补充：工作地点]'}\nRemuneration: ${p.pay || '[待补充：报酬]'}\nRoute: ${p.route || '待确认'}`;
  const timeline =
    events
      .map(
        (r) =>
          `${r.body.date || '日期待确认'} — ${r.body.title}\nMy role: ${r.body.role || '待确认'}\nAction: ${r.body.action || '待确认'}\nResult: ${r.body.result || '待确认'}\nTeam boundary: ${r.body.team || '待确认'}\nSources: ${(r.body.sourceIds || []).join(', ') || '来源待补充'}`,
      )
      .join('\n\n') || '尚无已确认的经历。';
  const issues =
    c.records
      .filter((r) => r.kind === 'evidence' && r.body.status !== 'reviewed')
      .map(
        (r) =>
          `${r.body.title}：${r.body.notes || '待核验原文、个人归因及适用要件'}`,
      )
      .join('\n') || '仍需专业复核完整记录与申请策略。';
  const matrix = CRITERIA.map(
    (k) =>
      `${k.title} (${k.term})\n核对：${k.check}\n相关材料：${
        evidence
          .filter((e) => e.body.criteria?.includes(k.id))
          .map((e) => e.body.title)
          .join('；') || '尚无已核对材料'
      }\n${k.caution}`,
  ).join('\n\n');
  const header = `${DOC_TYPES.find((x) => x[0] === type)?.[1] || '材料草稿'}\n准备稿 · 需事实、英文表达及专业复核 · ${new Date().toISOString().slice(0, 10)}\n该文档由已确认档案和材料组装；不代表法律资格判断、签署或已递交。\n\n`;
  let content = '';
  if (type === 'lawyer') content = lawyerBriefText(c, language);
  else if (type === 'i129')
    content = `I-129 FIELD WORKSHEET — NOT AN OFFICIAL FORM\n${snapshot}\n\nPart 1 — Petitioner information\nLegal name: ${p.company || '[待补充]'}\nMailing address / EIN / contact / authorized signatory: [待在官方表格中核对填写]\n\nPart 2 — Classification and requested action\nO-1A; requested action depends on confirmed route: ${p.route || '[待确认]'}\n\nPart 3 — Beneficiary information\nName: ${p.name || '[待补充]'}\nDate of birth, passport, I-94 and immigration history: [从原件核对，勿从模型推测]\n\nPart 5 — Proposed employment\n${snapshot}\n\nO/P Supplement / signatures / applicable additional sections\n[逐页核对适用问题与签字角色，不能跳过未列出的官方字段]\n\nReference copy: 02/27/26. Filing-day acceptance must be rechecked at https://www.uscis.gov/i-129 . This worksheet is not a complete reproduction of the form.`;
  else if (type === 'ss4')
    content = `SS-4 FIELD WORKSHEET — NOT AN OFFICIAL FORM\nLegal name: ${p.company || '[待补充]'}\nEntity / state: ${p.companyState || '[待确认]'}\n\nResponsible party / address / entity tax classification / reason for applying / accounting year / expected employees: [依IRS当前说明逐项确认]\n签字由真实授权人完成；使用适用的申请渠道；保留发送、失败和回复记录。\nhttps://www.irs.gov/forms-pubs/about-form-ss-4`;
  else if (type === 'work')
    content = `PROPOSED WORK ARRANGEMENT\n${snapshot}\n\nCompany-authorized signatory and authority: [待补充]\nActual work, locations, reporting and compensation terms must be confirmed by the parties. No signature is generated by USCOO.`;
  else if (type === 'support')
    content = `O-1A PETITION SUPPORT — FACT DRAFT\n${snapshot}\n\nProfessional history and personal contribution\n${timeline}\n\nEvidence to evaluate by criterion\n${matrix}\n\nTotality of the record\n[待专业复核：持续认可、领域地位及全部证据，不能以条数代替整体审查]\n\nEvidence references\n${refs.join('\n\n')}`;
  else if (type === 'recommendation')
    content = `RECOMMENDATION — AUTHOR BRIEF\n${snapshot}\n\nRecommender's identity, expertise and relationship: [待真实出具人确认]\nFirst-hand facts to describe:\n${timeline}\n\nSupporting sources:\n${refs.join('\n\n')}\n\n请真实出具人逐项核对其知情范围、具体事实和签署意愿。不得代签或杜撰评价。`;
  else if (type === 'business')
    content = `BUSINESS PLAN — FACT WORKSHEET\n${snapshot}\n\nProduct and intended activities: ${p.duties || '[待补充]'}\nMarket / customers / revenue / expenses / hiring / milestones: [仅填真实材料或明确假设，并标明依据]\n\nConfirmed background:\n${timeline}\n\nDo not present projections, company value or fundraising as historical personal achievements.`;
  else if (type === 'translation')
    content = `TRANSLATION CERTIFICATION WORKSHEET\n${evidence
      .filter((e) => e.body.language !== '英文')
      .map((e) => `${e.body.title}：${e.body.translation}`)
      .join(
        '\n',
      )}\n\n[译者姓名、语言能力、完整准确性声明、签字、日期：由真实译者确认]\n模型不能成为签署人；最终译文须完整对应原件。`;
  else if (type === 'consultation')
    content = `CONSULTATION REVIEW RECORD\nField: ${p.field || '[待补充]'}\nRelevant peer group / labor or management organization: [待判断]\nOpinion / applicable exception and authority: [待专业复核]\nAn ordinary recommendation letter is not automatically the required consultation.\nhttps://www.uscis.gov/policy-manual/volume-2-part-m-chapter-3`;
  else
    content = `RFE / NOID RESPONSE WORKSHEET\n${
      c.records
        .filter(
          (r) => r.kind === 'filing' && ['rfe', 'noid'].includes(r.body.event),
        )
        .map(
          (r) =>
            `${r.body.title}\n通知日期：${r.body.date}\n截止日：${r.body.deadline || '待核对通知原文'}\n期限已由用户核对：${r.body.deadlineConfirmed ? '是' : '否'}\n${r.body.notes || '逐项粘贴通知要求，并对应回复材料'}`,
        )
        .join('\n\n') || '[请先上传通知并核对实际期限]'
    }\n\n原论证与支持材料\n${refs.join('\n\n')}\n\n每个问题分别记录：原文位置、回复事实、来源、新附件、专业复核人与未决事项。`;
  return {
    title: DOC_TYPES.find((x) => x[0] === type)?.[1] || '材料草稿',
    type,
    content:
      (type === 'lawyer' && language === 'en'
        ? `Counsel brief · Preparation snapshot · ${new Date().toISOString().slice(0, 10)}\nIncludes self-reported leads and user-checked records with status labels. Not an eligibility determination or a filed petition.\n\n`
        : type === 'lawyer'
          ? `律所沟通包 · 准备快照 · ${new Date().toISOString().slice(0, 10)}\n包含本人自述、待核实方向及用户已核对记录；仍需结合完整材料复核，目前尚未递交。\n\n`
          : header) + content,
    state: 'working',
    sourceIds: evidence.map((x) => x.id),
    reviewedFacts: false,
    confirmed: false,
    stale: false,
  };
}
export function validateCanonical(
  body: any,
  records: RecordItem[],
  profile: Record<string, unknown> = {},
) {
  if (body.state !== 'canonical') return;
  if (
    body.type === 'lawyer' &&
    /线索，待核实|本人自述|尚未|待补充|待核对|待说明|待定|待确认|unverified|not (?:set|provided|checked)|to be (?:added|confirmed|decided)|needed/i.test(
      body.content,
    )
  )
    throw new HttpError(
      422,
      '律所沟通包仍包含待核实或缺失内容，请保留准备稿状态。',
    );
  if (!body.reviewedFacts || !body.confirmed)
    throw new HttpError(422, '请先核对全部事实和来源，再确认定稿。');
  if (/\[待|尚无已|来源待补充|\{\{|TODO|TBD/i.test(body.content))
    throw new HttpError(422, '草稿仍有待补内容，暂不能标为定稿。');
  for (const id of body.sourceIds || []) {
    const s = records.find((r) => r.id === id && r.kind === 'evidence');
    if (!s || s.body.status !== 'reviewed' || !s.body.confirmed)
      throw new HttpError(422, '引用中有尚未核对的材料，请先处理。');
  }
  if (!body.sourceIds?.length)
    throw new HttpError(422, '请为定稿绑定原始来源。');
  const numbers = (text: string) =>
    (text.match(/\b\d[\d,]*(?:\.\d+)?/g) || []).map((x) => x.replace(/,/g, ''));
  const supported = new Set(
    numbers(
      JSON.stringify(profile) +
        ' ' +
        new Date().toISOString().slice(0, 10) +
        ' ' +
        records
          .filter((r) => body.sourceIds.includes(r.id))
          .map((r) => r.body.excerpt || '')
          .join(' '),
    ),
  );
  const invented = numbers(body.content).filter(
    (x) => x.length >= 3 && !['129', '907'].includes(x) && !supported.has(x),
  );
  if (invented.length)
    throw new HttpError(
      422,
      '正文中有未能在档案或关联来源找到的数字。请补充原始依据后再定稿。',
    );
}
export async function docxBytes(title: string, content: string) {
  const children = content.split('\n').map(
    (line, i) =>
      new Paragraph({
        heading: i === 0 ? HeadingLevel.TITLE : undefined,
        spacing: { after: 120 },
        children: [new TextRun({ text: line, font: 'Arial', size: 22 })],
      }),
  );
  return new Uint8Array(
    await Packer.toArrayBuffer(
      new Document({
        creator: 'USCOO',
        title,
        styles: {
          default: {
            document: {
              run: { font: 'Arial', size: 22 },
              paragraph: { spacing: { line: 300 } },
            },
          },
        },
        sections: [
          {
            properties: {
              page: {
                margin: { top: 1000, bottom: 1000, left: 1100, right: 1100 },
              },
            },
            children,
          },
        ],
      }),
    ),
  );
}
const esc = (s: string) =>
  s.replace(
    /[&<>"']/g,
    (c) =>
      ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[
        c
      ]!,
  );
export function printHtml(title: string, content: string) {
  return `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="robots" content="noindex"><title>${esc(title)}</title><style>body{font:16px/1.8 system-ui,sans-serif;max-width:800px;margin:40px auto;padding:24px}pre{font:inherit;white-space:pre-wrap;overflow-wrap:anywhere}button{padding:10px 18px}@media print{button,.hint{display:none}@page{margin:20mm}body{margin:0;padding:0}}</style><button onclick="window.print()">打印 / 保存 PDF</button><p class="hint">可在打印对话框选择保存为 PDF。检查分页后使用。</p><pre>${esc(content)}</pre></html>`;
}
export async function exportCase(
  c: CaseData,
  includeFiles = true,
  language: Language = 'zh',
) {
  const files: Record<string, Uint8Array> = {},
    draft = buildDraft(c, 'lawyer', language);
  files['01-lawyer-brief.docx'] = await docxBytes(draft.title, draft.content);
  files['02-case-data.json'] = strToU8(JSON.stringify(c, null, 2));
  files['03-official-sources.txt'] = strToU8(
    OFFICIAL.map((x) => x.join('\n')).join('\n\n'),
  );
  const manifest: any[] = [];
  let total = 0;
  for (const r of c.records.filter((x) => x.kind === 'document')) {
    const bytes = await docxBytes(r.body.title, r.body.content);
    files[`documents/${r.id}.docx`] = bytes;
    manifest.push({
      id: r.id,
      title: r.body.title,
      version: r.version,
      state: r.body.state,
      hash: await hash(bytes.buffer as ArrayBuffer),
    });
  }
  if (includeFiles)
    for (const r of c.records.filter(
      (x) => x.kind === 'evidence' && x.body.file,
    )) {
      const f = r.body.file;
      total += f.size;
      if (total > 34 * 1024 * 1024)
        throw new HttpError(413, '附件较多，请逐份下载原件。');
      const object = await bindings().BUCKET.get(f.key);
      if (!object)
        throw new HttpError(503, '有原件暂时无法读取，未生成不完整的压缩包。');
      const bytes = await object.arrayBuffer();
      if ((await hash(bytes)) !== f.hash)
        throw new HttpError(503, '原件校验未通过，请先核对。');
      files[
        `originals/${r.id}-${f.name.replace(/[^\w.\-\u4e00-\u9fff]/g, '_')}`
      ] = new Uint8Array(bytes);
      manifest.push({
        id: r.id,
        title: r.body.title,
        version: r.version,
        hash: f.hash,
      });
    }
  files['04-manifest.json'] = strToU8(JSON.stringify(manifest, null, 2));
  files['README.txt'] = strToU8(
    'USCOO 私有项目导出。包含个人资料及原件，请仅向明确授权的人交付。准备包不是已递交申请；以每份文档状态、规则核验、真实签署和实际递交版本为准。官方表格需从USCIS取得适用版本并逐页回填核对。',
  );
  return zipSync(files, { level: 1 });
}
